In [1]:
X =   [[ 0.9573075 ,  0.83877059,  1.51767182],
       [ 0.83782936, -0.88288659,  0.7371596 ],
       [-0.01786695,  0.83195016,  0.66394427],
       [-2.43495362, -0.5999003 , -1.40044824],
       [-0.67749399, -0.93229581,  0.4736418 ],
       [ 0.47934903,  0.90244159, -0.24246888],
       [ 1.00280715, -0.68745287, -1.08115248],
       [ 0.98143632,  0.77163722,  0.07051186],
       [ 1.10721349,  0.37520477,  0.54710493],
       [ 0.20813717, -0.56000733, -0.38301232]]

In [2]:
from statistics import mean
def Sum_for(data):
  avgList = []
  avg = 0
  for i in data:
    avg =+ mean(i)
    avgList.append(avg)
  return avgList

z = Sum_for(X)
print(z)

[1.1045833033333332, 0.23070079, 0.49267582666666665, -1.4784340533333333, -0.378716, 0.3797739133333333, -0.2552660666666667, 0.6078618, 0.67650773, -0.2449608266666667]


In [3]:
import numpy as np

def Sum_Numpy(data):
  a = np.array(data)
  sum = np.average(a, axis = 1)
  return sum

g = Sum_Numpy(X)
print(g)

[ 1.1045833   0.23070079  0.49267583 -1.47843405 -0.378716    0.37977391
 -0.25526607  0.6078618   0.67650773 -0.24496083]


In [4]:
A =   [[-0.92597499,  0.43720423, -0.35210601],
       [-1.57649123, -1.07509224,  0.47516471],
       [-0.20934054,  1.02077567,  1.07644301],
       [-0.15567112, -2.55700368, -1.46401899],
       [ 0.02719893,  0.19837065,  1.85917993],
       [-0.48220856, -0.5882894 ,  0.8520666 ],
       [-0.61637754, -1.28843955,  0.21051033],
       [-0.37856032, -0.18264039, -1.66748906],
       [-1.88442764,  1.06363804, -0.73199025],
       [ 1.1067878 , -1.50124564,  0.3577191 ]]
       
B =   [[ 0.83755816, -1.00443884, -0.50455401],
       [ 0.17677451,  0.31791523,  0.87857933],
       [-0.79809369,  1.05786099,  1.23321483],
       [ 2.15225423,  0.03105143, -1.62707639],
       [-0.38475992,  0.52332967, -0.80852807],
       [-0.33078515, -0.39291109,  0.92239671],
       [-0.68534134,  1.42376764, -0.56941844],
       [-0.96316595, -0.9312169 , -0.6153402 ],
       [ 0.11725929,  0.12216484,  0.22910712],
       [-0.79512535,  1.4075714 , -0.53488747]]

In [5]:

def Element_add(list1, list2):
  result = [[list1[i][j] + list2[i][j]  for j in range
  (len(X[0]))] for i in range(len(X))]
  return result

t = Element_add(A,B)
print(t)

[[-0.08841683, -0.5672346099999999, -0.8566600200000001], [-1.39971672, -0.75717701, 1.35374404], [-1.0074342299999999, 2.07863666, 2.30965784], [1.99658311, -2.5259522499999996, -3.09109538], [-0.35756098999999997, 0.72170032, 1.0506518599999999], [-0.81299371, -0.98120049, 1.77446331], [-1.3017188800000001, 0.1353280899999998, -0.35890811], [-1.34172627, -1.11385729, -2.28282926], [-1.76716835, 1.18580288, -0.50288313], [0.31166245000000004, -0.09367424000000013, -0.17716837000000002]]


In [6]:
def Element_Numpy(list1, list2):
  return np.add(list1, list2)

print(Element_Numpy(A, B))


[[-0.08841683 -0.56723461 -0.85666002]
 [-1.39971672 -0.75717701  1.35374404]
 [-1.00743423  2.07863666  2.30965784]
 [ 1.99658311 -2.52595225 -3.09109538]
 [-0.35756099  0.72170032  1.05065186]
 [-0.81299371 -0.98120049  1.77446331]
 [-1.30171888  0.13532809 -0.35890811]
 [-1.34172627 -1.11385729 -2.28282926]
 [-1.76716835  1.18580288 -0.50288313]
 [ 0.31166245 -0.09367424 -0.17716837]]


In [7]:
a = [4, 2, 6, 2, 5, 7, 5, 8, 8, 4]
b = [0, 6, 15, 3, 4, 6, 10, 8, 8, 18]

In [8]:
def Dot_add(list1, list2):
  sum = 0
  for i in range(len(list1)):
    sum += list1[i] * list2[i]
  return sum

print(Dot_add(a, b))


420


In [9]:
def Dot_Numpy(list1, list2) :
  return np.dot(list1, list2)


print(Dot_Numpy(a, b))

420


In [10]:
A = [[1,2],
    [2,1]]
B = [[3],
    [1]]

In [11]:
def multiply(list1, list2):
  result = []
  for i in range(0,len(list1)):
      temp=[]
      for j in range(0,len(list2[0])):
          s = 0
          for k in range(0,len(list1[0])):
            s += list1[i][k]*list2[k][j]
          temp.append(s)
      result.append(temp)
  return result

print(multiply(A,B))

[[5], [7]]


In [12]:
def multiply_Numpy(list1, list2):
  return np.matmul(list1,list2)

print(multiply_Numpy(A,B))

[[5]
 [7]]
